### PR TITLE
added documentation for login endpoints

### PR DESCRIPTION
**Pull request by Olivernyu**

### CODE REVIEW

**Review by Alex-YuYan — COMMENTED** [review]
It seems to me that the login/login documentation looks not quite right on swagger

**Comment by Olivernyu** [comment]
> It seems to me that the login/login documentation looks not quite right on swagger

What do you mena by 'not quite right'

**Review by Alex-YuYan — APPROVED** [review]
lgtm

**Review by TomY-Zhang — APPROVED** [review]
lgtm

**Pull request merged**
